export interface Employee {
  id: number
  firstName: string
  lastName: string
  email: string
  department: string
  role: string
}

export const mockEmployees: Employee[] = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@company.com",
    department: "IT",
    role: "Manager",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@company.com",
    department: "HR",
    role: "Specialist",
  },
  {
    id: 3,
    firstName: "Mike",
    lastName: "Johnson",
    email: "mike.johnson@company.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 4,
    firstName: "Sarah",
    lastName: "Williams",
    email: "sarah.williams@company.com",
    department: "Marketing",
    role: "Coordinator",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@company.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 6,
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@company.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 7,
    firstName: "Chris",
    lastName: "Wilson",
    email: "chris.wilson@company.com",
    department: "Operations",
    role: "Specialist",
  },
  {
    id: 8,
    firstName: "Lisa",
    lastName: "Garcia",
    email: "lisa.garcia@company.com",
    department: "Finance",
    role: "Manager",
  },
  {
    id: 9,
    firstName: "Tom",
    lastName: "Martinez",
    email: "tom.martinez@company.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 10,
    firstName: "Anna",
    lastName: "Rodriguez",
    email: "anna.rodriguez@company.com",
    department: "Marketing",
    role: "Specialist",
  },
  {
    id: 11,
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@company.com",
    department: "Operations",
    role: "Manager",
  },
  {
    id: 12,
    firstName: "Maria",
    lastName: "Taylor",
    email: "maria.taylor@company.com",
    department: "HR",
    role: "Coordinator",
  },
  {
    id: 13,
    firstName: "Robert",
    lastName: "Thomas",
    email: "robert.thomas@company.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 14,
    firstName: "Jennifer",
    lastName: "Jackson",
    email: "jennifer.jackson@company.com",
    department: "IT",
    role: "Developer",
  },
  {
    id: 15,
    firstName: "Michael",
    lastName: "White",
    email: "michael.white@company.com",
    department: "Marketing",
    role: "Manager",
  },
  {
    id: 16,
    firstName: "Jessica",
    lastName: "Harris",
    email: "jessica.harris@company.com",
    department: "Operations",
    role: "Coordinator",
  },
  {
    id: 17,
    firstName: "William",
    lastName: "Martin",
    email: "william.martin@company.com",
    department: "HR",
    role: "Analyst",
  },
  {
    id: 18,
    firstName: "Ashley",
    lastName: "Thompson",
    email: "ashley.thompson@company.com",
    department: "Finance",
    role: "Specialist",
  },
  {
    id: 19,
    firstName: "Daniel",
    lastName: "Garcia",
    email: "daniel.garcia@company.com",
    department: "IT",
    role: "Manager",
  },
  {
    id: 20,
    firstName: "Amanda",
    lastName: "Martinez",
    email: "amanda.martinez@company.com",
    department: "Marketing",
    role: "Developer",
  },
]
